title: Dino's Pond
description: Looking to the stars <3
theme: jekyll-theme-cayman

show_downloads: true
github:
  mainpage_url: https://its-me-dineo.github.io/
  twitter_url: https://twitter.com/dinospond