title: Dino's Pond
description: Welcome to me so far <3
theme: jekyll-theme-cayman

show_downloads: true
github:
  zip_url: https://twitter.com/dinospond
  tar_url: https://its-me-dineo.github.io/